### ISSUE TITLE
Pack and sticker IDs are too big for JavaScript

### ISSUE THREAD

**Issue by Bubu** [maunium/stickerpicker#12]
It scrolls to the first pack visible in the horizontal scroll bar. Both on android and Web. Possibly related: selecting the second to last pack also selects the same first in line pack. (but it scrolls correctly)

**Comment by tulir** [comment]
It works fine for me :thinking: 

There's no actual code for scrolling anywhere (except on iOS), it's just `<a href="#pack-123">`

The "selection" underlines all packs that are currently visible

**Comment by Bubu** [comment]
Screencast of the problem: https://cloud.bubu1.eu/s/AE3BT3wS7RYcczi

**Comment by tulir** [comment]
So the issue is that Telegram sticker pack and file IDs are designed to be stored as 64-bit ints, but JS only supports 53-bit ints.
