### ISSUE TITLE
Nicer darkmode support

### ISSUE THREAD

**Issue by Rafaeltheraven** [maunium/stickerpicker#17]
The stickerpicker looks quite nice using light mode, but when using darkmode the text for the stickerpacks bleeds into the background and the top bar stays an oddly contrasted white. Might be good to consider just enforcing a white background or changing the text to white if the background is dark (though I'm not sure how feasible that is).
![image](https://user-images.githubusercontent.com/10010899/92897203-4bbb0c80-f41d-11ea-892d-e8fc4bf451ea.png)

**Comment by tulir** [comment]
There's currently no support for dark themes. The navbar having an explicit background color isn't necessary anymore, but I'm not exactly sure how to detect the app theme in widgets to fix the text and icon color

**Comment by Rafaeltheraven** [comment]
I kind of assumed that would be impossible, but perhaps consider setting
```
body {
background-color: white
}
```
this enforces a white background regardless of client settings, which works in both light and dark mode.
![image](https://user-images.githubusercontent.com/10010899/92899754-61313600-f41f-11ea-9bdf-3f88c6634bd6.png)
