### ISSUE TITLE
Integrated gif search

### ISSUE THREAD

**Issue by tulir** [maunium/stickerpicker#22]
Something like Giphy could be integrated into the sticker picker to provide a better gif sending experience than the bots that can't do previews. Should be optional, since it requires connecting to an external service.

**Comment by hegdenischay** [comment]
I'm implementing this for myself here: https://github.com/hegdenischay/stickerpicker/tree/gif-search-matrix-widget-api

Not sure how we should go with replacing the hardcoded API key that I have there. I was wondering some kind of config to set the API key like what we have in the config file, but this API key is simply something I got out of a single request and not really identifying information, so should it be disabled if the API key isn't mentioned or simply use the existing API key?

**Comment by hegdenischay** [comment]
This is how it now looks if no API key was set in the config:
![image](https://github.com/maunium/stickerpicker/assets/28584388/a39afe96-af7d-4bf4-a5f2-bbd1d8ac45f4)
And this is how it looks if an API key _was_ set.
![image](https://github.com/maunium/stickerpicker/assets/28584388/8a9060e3-d86d-4eda-85df-8b1c355cdd98)
Any help would be very much appreciated.
