### ISSUE TITLE
no stickers on element-desktop/schildichat-desktop

### ISSUE THREAD

**Issue by benneti** [maunium/stickerpicker#33]
Hi I created the static page as described and added the widget but in the desktop apps only the background loads.
I think the error might not be me because in the mobile app everything works as intended.
(I am using dracula theme in the desktop app but disabling it did not help)
To make sure the problem is not in my desktop installations you could try the stickers from 
https://cloud.tissot.de/stickerpicker/ .

**Comment by tulir** [comment]
> x-frame-options: SAMEORIGIN

That means any web app outside of cloud.tissot.de can't show the sticker picker. Non-web apps don't care, which is why it works on mobile

**Comment by benneti** [comment]
Ah perfect, thank you for this information now it works!
