### ISSUE TITLE
Sticker not always showing in conversation

### ISSUE THREAD

**Issue by floviolleau** [maunium/stickerpicker#47]
Hi,

Thanks for your amazing project !
It will help me lot and will be very useful.

I have a small issue. I read your wiki and used your demo url. All is working fine except one strange thing.

## Steps to reproduce:
- follow wiki documentation
- restart Element Desktop app
- chose and post a sticker

## Issue
Some "families" of stickers are working, some not.
- pusheen: :red_circle: not working
- His Dark Materials: :red_circle: not working
- Loading Artist: :green_circle: working
- Rabbit: :green_circle: working

![image](https://user-images.githubusercontent.com/5442973/167836158-7cbd3715-d1f9-42c0-908d-510d48a3912d.png)

Thanks!

**Comment by tulir** [comment]
Sounds like a federation issue on your server

**Comment by floviolleau** [comment]
Hi,

I'm not using federation at all. I live in my own ecosystem :)

**Comment by tulir** [comment]
The stickers don't just appear out of nowhere, the example packs have media from matrix.org and maunium.net. You have to make the packs yourself (or import from telegram yourself) to upload the media directly to your server

**Comment by floviolleau** [comment]
OK thanks. It was just a test to see if all was working as expecting. I will do my own thanks!
