### ISSUE TITLE
sticker-pack invalid syntax

### ISSUE THREAD

**Issue by Andruegoing** [maunium/stickerpicker#61]
The same problem #27  occurs in sticker-pack 

```
>>> sticker-pack kim

  File "<stdin>", line 1
    sticker-pack kim
                 ^^^
SyntaxError: invalid syntax
```

I did a successful packaging test two days ago, but I can't remember the user permission relationship used, the problem may be related to this

**Comment by Andruegoing** [comment]
When I type `sticker-pack` I get 
```
>>> sticker-pack
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
NameError: name 'sticker' is not defined
```

**Comment by tulir** [comment]
`sticker-pack` is a shell command that runs a python script, not something to run inside python.
